// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3S5Sb1zAD6o5Ze-RU0SVC_o3OzmQ7w-U',
    appId: '1:563105549705:web:0b94ce1eb0ab3c9d856558',
    messagingSenderId: '563105549705',
    projectId: 'chat-app-74a96',
    authDomain: 'chat-app-74a96.firebaseapp.com',
    storageBucket: 'chat-app-74a96.appspot.com',
    measurementId: 'G-4WNDHBCPGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwhsEp7IwDyA2HN-0dLGxdiqh8tXcmKAU',
    appId: '1:563105549705:android:8f1fecd4cb167445856558',
    messagingSenderId: '563105549705',
    projectId: 'chat-app-74a96',
    storageBucket: 'chat-app-74a96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8QAn1wsqZB_hp27yWh2yYS5LV_WqMMMk',
    appId: '1:563105549705:ios:dcc9c75df096cfbb856558',
    messagingSenderId: '563105549705',
    projectId: 'chat-app-74a96',
    storageBucket: 'chat-app-74a96.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8QAn1wsqZB_hp27yWh2yYS5LV_WqMMMk',
    appId: '1:563105549705:ios:dcc9c75df096cfbb856558',
    messagingSenderId: '563105549705',
    projectId: 'chat-app-74a96',
    storageBucket: 'chat-app-74a96.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3S5Sb1zAD6o5Ze-RU0SVC_o3OzmQ7w-U',
    appId: '1:563105549705:web:1d226b684d99a626856558',
    messagingSenderId: '563105549705',
    projectId: 'chat-app-74a96',
    authDomain: 'chat-app-74a96.firebaseapp.com',
    storageBucket: 'chat-app-74a96.appspot.com',
    measurementId: 'G-XLCMHSTES0',
  );

}